version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-app:latest
    container_name: chat-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network
    command: >
      sh -c "
        npm run db:migrate &&
        node dist/server.js
      "

  db:
    image: postgres:17-alpine3.20
    container_name: chat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
